<a href="https://colab.research.google.com/github/faridaarum/Tubes-SA/blob/main/TubesSA(fix).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from itertools import chain
from itertools import combinations

In [ ]:
# https://docs.google.com/spreadsheets/d/1-vgsgUO1PruDPNzfaQuz3KBMFS_VJ8AK/edit?usp=sharing&ouid=107087075363920335686&rtpof=true&sd=true
!gdown --id 1-vgsgUO1PruDPNzfaQuz3KBMFS_VJ8AK

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1-vgsgUO1PruDPNzfaQuz3KBMFS_VJ8AK

In [ ]:
# memanggil library pandas untuk membaca dil bengkel.xlsx
df = pd.read_excel('./data diet.xlsx')
df.head()

   No    Makanan  Kalori  Karbohidrat  Harga  Profit
0   1    Alpukat     102            0   5000    20.4
1   2  Ayam dada     332            0  10000    33.2
2   3      Bayam      19            3  10000     1.9
3   4      bebek     641            0  19000    33.8
4   5    brokoli      27            3  10000     2.7

In [ ]:
sort_profit = df.sort_values(["Profit"], ascending=False)
sort_profit = sort_profit.reset_index()
sort_profit = sort_profit.drop("index", axis=1)
sort_profit

   No         Makanan  Kalori  Karbohidrat  Harga  Profit
0   4           bebek     641            0  19000    33.8
1   2       Ayam dada     332            0  10000    33.2
2   6     Daging Sapi     500            0  20000    25.0
3   9    Keju Cheddar     114            1   5000    22.8
4   1         Alpukat     102            0   5000    20.4
5  10          Salmon     257            0  30000     8.6
6   5         brokoli      27            3  10000     2.7
7   3           Bayam      19            3  10000     1.9
8   7   Jamur Kancing      15            2  10000     1.5
9   8  Kacang Panjang      22            4  10000     1.5

In [ ]:
sort_harga = df.sort_values(["Harga"], ascending=True)
sort_harga = sort_harga.reset_index()
sort_harga = sort_harga.drop("index", axis=1)
sort_harga

   No         Makanan  Kalori  Karbohidrat  Harga  Profit
0   1         Alpukat     102            0   5000    20.4
1   9    Keju Cheddar     114            1   5000    22.8
2   2       Ayam dada     332            0  10000    33.2
3   3           Bayam      19            3  10000     1.9
4   5         brokoli      27            3  10000     2.7
5   7   Jamur Kancing      15            2  10000     1.5
6   8  Kacang Panjang      22            4  10000     1.5
7   4           bebek     641            0  19000    33.8
8   6     Daging Sapi     500            0  20000    25.0
9  10          Salmon     257            0  30000     8.6

# BRUTE FORCE

In [ ]:
len(df)

10

In [ ]:
items = df["No"]

In [ ]:
def powerset(items):
  res = [[]]
  for item in items:
    newset = [r+[item] for r in res]
    res.extend(newset)
  return res

In [ ]:
print(powerset(items))

[[], [1], [2], [1, 2], [3], [1, 3], [2, 3], [1, 2, 3], [4], [1, 4], [2, 4], [1, 2, 4], [3, 4], [1, 3, 4], [2, 3, 4], [1, 2, 3, 4], [5], [1, 5], [2, 5], [1, 2, 5], [3, 5], [1, 3, 5], [2, 3, 5], [1, 2, 3, 5], [4, 5], [1, 4, 5], [2, 4, 5], [1, 2, 4, 5], [3, 4, 5], [1, 3, 4, 5], [2, 3, 4, 5], [1, 2, 3, 4, 5], [6], [1, 6], [2, 6], [1, 2, 6], [3, 6], [1, 3, 6], [2, 3, 6], [1, 2, 3, 6], [4, 6], [1, 4, 6], [2, 4, 6], [1, 2, 4, 6], [3, 4, 6], [1, 3, 4, 6], [2, 3, 4, 6], [1, 2, 3, 4, 6], [5, 6], [1, 5, 6], [2, 5, 6], [1, 2, 5, 6], [3, 5, 6], [1, 3, 5, 6], [2, 3, 5, 6], [1, 2, 3, 5, 6], [4, 5, 6], [1, 4, 5, 6], [2, 4, 5, 6], [1, 2, 4, 5, 6], [3, 4, 5, 6], [1, 3, 4, 5, 6], [2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], [7], [1, 7], [2, 7], [1, 2, 7], [3, 7], [1, 3, 7], [2, 3, 7], [1, 2, 3, 7], [4, 7], [1, 4, 7], [2, 4, 7], [1, 2, 4, 7], [3, 4, 7], [1, 3, 4, 7], [2, 3, 4, 7], [1, 2, 3, 4, 7], [5, 7], [1, 5, 7], [2, 5, 7], [1, 2, 5, 7], [3, 5, 7], [1, 3, 5, 7], [2, 3, 5, 7], [1, 2, 3, 5, 7], [4, 5, 7], [1, 4, 5, 7], [2, 4, 5, 7], [1, 2, 4, 5, 7], [3, 4, 5, 7], [1, 3, 4, 5, 7], [2, 3, 4, 5, 7], [1, 2, 3, 4, 5, 7], [6, 7], [1, 6, 7], [2, 6, 7], [1, 2, 6, 7], [3, 6, 7], [1, 3, 6, 7], [2, 3, 6, 7], [1, 2, 3, 6, 7], [4, 6, 7], [1, 4, 6, 7], [2, 4, 6, 7], [1, 2, 4, 6, 7], [3, 4, 6, 7], [1, 3, 4, 6, 7], [2, 3, 4, 6, 7], [1, 2, 3, 4, 6, 7], [5, 6, 7], [1, 5, 6, 7], [2, 5, 6, 7], [1, 2, 5, 6, 7], [3, 5, 6, 7], [1, 3, 5, 6, 7], [2, 3, 5, 6, 7], [1, 2, 3, 5, 6, 7], [4, 5, 6, 7], [1, 4, 5, 6, 7], [2, 4, 5, 6, 7], [1, 2, 4, 5, 6, 7], [3, 4, 5, 6, 7], [1, 3, 4, 5, 6, 7], [2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7], [8], [1, 8], [2, 8], [1, 2, 8], [3, 8], [1, 3, 8], [2, 3, 8], [1, 2, 3, 8], [4, 8], [1, 4, 8], [2, 4, 8], [1, 2, 4, 8], [3, 4, 8], [1, 3, 4, 8], [2, 3, 4, 8], [1, 2, 3, 4, 8], [5, 8], [1, 5, 8], [2, 5, 8], [1, 2, 5, 8], [3, 5, 8], [1, 3, 5, 8], [2, 3, 5, 8], [1, 2, 3, 5, 8], [4, 5, 8], [1, 4, 5, 8], [2, 4, 5, 8], [1, 2, 4, 5, 8], [3, 4, 5, 8], [1, 3, 4, 5, 8], [2, 3, 4, 5, 8], [1, 2, 3, 4, 5, 8], [6, 8], [1, 6, 8], [2, 6, 8], [1, 2, 6, 8], [3, 6, 8], [1, 3, 6, 8], [2, 3, 6, 8], [1, 2, 3, 6, 8], [4, 6, 8], [1, 4, 6, 8], [2, 4, 6, 8], [1, 2, 4, 6, 8], [3, 4, 6, 8], [1, 3, 4, 6, 8], [2, 3, 4, 6, 8], [1, 2, 3, 4, 6, 8], [5, 6, 8], [1, 5, 6, 8], [2, 5, 6, 8], [1, 2, 5, 6, 8], [3, 5, 6, 8], [1, 3, 5, 6, 8], [2, 3, 5, 6, 8], [1, 2, 3, 5, 6, 8], [4, 5, 6, 8], [1, 4, 5, 6, 8], [2, 4, 5, 6, 8], [1, 2, 4, 5, 6, 8], [3, 4, 5, 6, 8], [1, 3, 4, 5, 6, 8], [2, 3, 4, 5, 6, 8], [1, 2, 3, 4, 5, 6, 8], [7, 8], [1, 7, 8], [2, 7, 8], [1, 2, 7, 8], [3, 7, 8], [1, 3, 7, 8], [2, 3, 7, 8], [1, 2, 3, 7, 8], [4, 7, 8], [1, 4, 7, 8], [2, 4, 7, 8], [1, 2, 4, 7, 8], [3, 4, 7, 8], [1, 3, 4, 7, 8], [2, 3, 4, 7, 8], [1, 2, 3, 4, 7, 8], [5, 7, 8], [1, 5, 7, 8], [2, 5, 7, 8], [1, 2, 5, 7, 8], [3, 5, 7, 8], [1, 3, 5, 7, 8], [2, 3, 5, 7, 8], [1, 2, 3, 5, 7, 8], [4, 5, 7, 8], [1, 4, 5, 7, 8], [2, 4, 5, 7, 8], [1, 2, 4, 5, 7, 8], [3, 4, 5, 7, 8], [1, 3, 4, 5, 7, 8], [2, 3, 4, 5, 7, 8], [1, 2, 3, 4, 5, 7, 8], [6, 7, 8], [1, 6, 7, 8], [2, 6, 7, 8], [1, 2, 6, 7, 8], [3, 6, 7, 8], [1, 3, 6, 7, 8], [2, 3, 6, 7, 8], [1, 2, 3, 6, 7, 8], [4, 6, 7, 8], [1, 4, 6, 7, 8], [2, 4, 6, 7, 8], [1, 2, 4, 6, 7, 8], [3, 4, 6, 7, 8], [1, 3, 4, 6, 7, 8], [2, 3, 4, 6, 7, 8], [1, 2, 3, 4, 6, 7, 8], [5, 6, 7, 8], [1, 5, 6, 7, 8], [2, 5, 6, 7, 8], [1, 2, 5, 6, 7, 8], [3, 5, 6, 7, 8], [1, 3, 5, 6, 7, 8], [2, 3, 5, 6, 7, 8], [1, 2, 3, 5, 6, 7, 8], [4, 5, 6, 7, 8], [1, 4, 5, 6, 7, 8], [2, 4, 5, 6, 7, 8], [1, 2, 4, 5, 6, 7, 8], [3, 4, 5, 6, 7, 8], [1, 3, 4, 5, 6, 7, 8], [2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8], [9], [1, 9], [2, 9], [1, 2, 9], [3, 9], [1, 3, 9], [2, 3, 9], [1, 2, 3, 9], [4, 9], [1, 4, 9], [2, 4, 9], [1, 2, 4, 9], [3, 4, 9], [1, 3, 4, 9], [2, 3, 4, 9], [1, 2, 3, 4, 9], [5, 9], [1, 5, 9], [2, 5, 9], [1, 2, 5, 9], [3, 5, 9], [1, 3, 5, 9], [2, 3, 5, 9], [1, 2, 3, 5, 9], [4, 5, 9], [1, 4, 5, 9], [2, 4, 5, 9], [1, 2, 4, 5, 9], [3, 4, 5, 9], [1, 3, 4, 5, 9], [2, 3, 4, 5, 9], [1, 2, 3, 4, 5, 9], [6, 9], [1, 6, 9], [2, 6, 9], [1, 2, 6, 9], [3, 6, 9], [1, 3, 6, 9], [2, 3, 6, 9], [1, 2, 3, 6, 9], [4, 6, 9], [1, 4, 6, 9], [2, 4, 6, 9], [1, 2, 4, 6, 9], [3, 4, 6, 9], [1, 3, 4, 6, 9], [2, 3, 4, 6, 9], [1, 2, 3, 4, 6, 9], [5, 6, 9], [1, 5, 6, 9], [2, 5, 6, 9], [1, 2, 5, 6, 9], [3, 5, 6, 9], [1, 3, 5, 6, 9], [2, 3, 5, 6, 9], [1, 2, 3, 5, 6, 9], [4, 5, 6, 9], [1, 4, 5, 6, 9], [2, 4, 5, 6, 9], [1, 2, 4, 5, 6, 9], [3, 4, 5, 6, 9], [1, 3, 4, 5, 6, 9], [2, 3, 4, 5, 6, 9], [1, 2, 3, 4, 5, 6, 9], [7, 9], [1, 7, 9], [2, 7, 9], [1, 2, 7, 9], [3, 7, 9], [1, 3, 7, 9], [2, 3, 7, 9], [1, 2, 3, 7, 9], [4, 7, 9], [1, 4, 7, 9], [2, 4, 7, 9], [1, 2, 4, 7, 9], [3, 4, 7, 9], [1, 3, 4, 7, 9], [2, 3, 4, 7, 9], [1, 2, 3, 4, 7, 9], [5, 7, 9], [1, 5, 7, 9], [2, 5, 7, 9], [1, 2, 5, 7, 9], [3, 5, 7, 9], [1, 3, 5, 7, 9], [2, 3, 5, 7, 9], [1, 2, 3, 5, 7, 9], [4, 5, 7, 9], [1, 4, 5, 7, 9], [2, 4, 5, 7, 9], [1, 2, 4, 5, 7, 9], [3, 4, 5, 7, 9], [1, 3, 4, 5, 7, 9], [2, 3, 4, 5, 7, 9], [1, 2, 3, 4, 5, 7, 9], [6, 7, 9], [1, 6, 7, 9], [2, 6, 7, 9], [1, 2, 6, 7, 9], [3, 6, 7, 9], [1, 3, 6, 7, 9], [2, 3, 6, 7, 9], [1, 2, 3, 6, 7, 9], [4, 6, 7, 9], [1, 4, 6, 7, 9], [2, 4, 6, 7, 9], [1, 2, 4, 6, 7, 9], [3, 4, 6, 7, 9], [1, 3, 4, 6, 7, 9], [2, 3, 4, 6, 7, 9], [1, 2, 3, 4, 6, 7, 9], [5, 6, 7, 9], [1, 5, 6, 7, 9], [2, 5, 6, 7, 9], [1, 2, 5, 6, 7, 9], [3, 5, 6, 7, 9], [1, 3, 5, 6, 7, 9], [2, 3, 5, 6, 7, 9], [1, 2, 3, 5, 6, 7, 9], [4, 5, 6, 7, 9], [1, 4, 5, 6, 7, 9], [2, 4, 5, 6, 7, 9], [1, 2, 4, 5, 6, 7, 9], [3, 4, 5, 6, 7, 9], [1, 3, 4, 5, 6, 7, 9], [2, 3, 4, 5, 6, 7, 9], [1, 2, 3, 4, 5, 6, 7, 9], [8, 9], [1, 8, 9], [2, 8, 9], [1, 2, 8, 9], [3, 8, 9], [1, 3, 8, 9], [2, 3, 8, 9], [1, 2, 3, 8, 9], [4, 8, 9], [1, 4, 8, 9], [2, 4, 8, 9], [1, 2, 4, 8, 9], [3, 4, 8, 9], [1, 3, 4, 8, 9], [2, 3, 4, 8, 9], [1, 2, 3, 4, 8, 9], [5, 8, 9], [1, 5, 8, 9], [2, 5, 8, 9], [1, 2, 5, 8, 9], [3, 5, 8, 9], [1, 3, 5, 8, 9], [2, 3, 5, 8, 9], [1, 2, 3, 5, 8, 9], [4, 5, 8, 9], [1, 4, 5, 8, 9], [2, 4, 5, 8, 9], [1, 2, 4, 5, 8, 9], [3, 4, 5, 8, 9], [1, 3, 4, 5, 8, 9], [2, 3, 4, 5, 8, 9], [1, 2, 3, 4, 5, 8, 9], [6, 8, 9], [1, 6, 8, 9], [2, 6, 8, 9], [1, 2, 6, 8, 9], [3, 6, 8, 9], [1, 3, 6, 8, 9], [2, 3, 6, 8, 9], [1, 2, 3, 6, 8, 9], [4, 6, 8, 9], [1, 4, 6, 8, 9], [2, 4, 6, 8, 9], [1, 2, 4, 6, 8, 9], [3, 4, 6, 8, 9], [1, 3, 4, 6, 8, 9], [2, 3, 4, 6, 8, 9], [1, 2, 3, 4, 6, 8, 9], [5, 6, 8, 9], [1, 5, 6, 8, 9], [2, 5, 6, 8, 9], [1, 2, 5, 6, 8, 9], [3, 5, 6, 8, 9], [1, 3, 5, 6, 8, 9], [2, 3, 5, 6, 8, 9], [1, 2, 3, 5, 6, 8, 9], [4, 5, 6, 8, 9], [1, 4, 5, 6, 8, 9], [2, 4, 5, 6, 8, 9], [1, 2, 4, 5, 6, 8, 9], [3, 4, 5, 6, 8, 9], [1, 3, 4, 5, 6, 8, 9], [2, 3, 4, 5, 6, 8, 9], [1, 2, 3, 4, 5, 6, 8, 9], [7, 8, 9], [1, 7, 8, 9], [2, 7, 8, 9], [1, 2, 7, 8, 9], [3, 7, 8, 9], [1, 3, 7, 8, 9], [2, 3, 7, 8, 9], [1, 2, 3, 7, 8, 9], [4, 7, 8, 9], [1, 4, 7, 8, 9], [2, 4, 7, 8, 9], [1, 2, 4, 7, 8, 9], [3, 4, 7, 8, 9], [1, 3, 4, 7, 8, 9], [2, 3, 4, 7, 8, 9], [1, 2, 3, 4, 7, 8, 9], [5, 7, 8, 9], [1, 5, 7, 8, 9], [2, 5, 7, 8, 9], [1, 2, 5, 7, 8, 9], [3, 5, 7, 8, 9], [1, 3, 5, 7, 8, 9], [2, 3, 5, 7, 8, 9], [1, 2, 3, 5, 7, 8, 9], [4, 5, 7, 8, 9], [1, 4, 5, 7, 8, 9], [2, 4, 5, 7, 8, 9], [1, 2, 4, 5, 7, 8, 9], [3, 4, 5, 7, 8, 9], [1, 3, 4, 5, 7, 8, 9], [2, 3, 4, 5, 7, 8, 9], [1, 2, 3, 4, 5, 7, 8, 9], [6, 7, 8, 9], [1, 6, 7, 8, 9], [2, 6, 7, 8, 9], [1, 2, 6, 7, 8, 9], [3, 6, 7, 8, 9], [1, 3, 6, 7, 8, 9], [2, 3, 6, 7, 8, 9], [1, 2, 3, 6, 7, 8, 9], [4, 6, 7, 8, 9], [1, 4, 6, 7, 8, 9], [2, 4, 6, 7, 8, 9], [1, 2, 4, 6, 7, 8, 9], [3, 4, 6, 7, 8, 9], [1, 3, 4, 6, 7, 8, 9], [2, 3, 4, 6, 7, 8, 9], [1, 2, 3, 4, 6, 7, 8, 9], [5, 6, 7, 8, 9], [1, 5, 6, 7, 8, 9], [2, 5, 6, 7, 8, 9], [1, 2, 5, 6, 7, 8, 9], [3, 5, 6, 7, 8, 9], [1, 3, 5, 6, 7, 8, 9], [2, 3, 5, 6, 7, 8, 9], [1, 2, 3, 5, 6, 7, 8, 9], [4, 5, 6, 7, 8, 9], [1, 4, 5, 6, 7, 8, 9], [2, 4, 5, 6, 7, 8, 9], [1, 2, 4, 5, 6, 7, 8, 9], [3, 4, 5, 6, 7, 8, 9], [1, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9], [10], [1, 10], [2, 10], [1, 2, 10], [3, 10], [1, 3, 10], [2, 3, 10], [1, 2, 3, 10], [4, 10], [1, 4, 10], [2, 4, 10], [1, 2, 4, 10], [3, 4, 10], [1, 3, 4, 10], [2, 3, 4, 10], [1, 2, 3, 4, 10], [5, 10], [1, 5, 10], [2, 5, 10], [1, 2, 5, 10], [3, 5, 10], [1, 3, 5, 10], [2, 3, 5, 10], [1, 2, 3, 5, 10], [4, 5, 10], [1, 4, 5, 10], [2, 4, 5, 10], [1, 2, 4, 5, 10], [3, 4, 5, 10], [1, 3, 4, 5, 10], [2, 3, 4, 5, 10], [1, 2, 3, 4, 5, 10], [6, 10], [1, 6, 10], [2, 6, 10], [1, 2, 6, 10], [3, 6, 10], [1, 3, 6, 10], [2, 3, 6, 10], [1, 2, 3, 6, 10], [4, 6, 10], [1, 4, 6, 10], [2, 4, 6, 10], [1, 2, 4, 6, 10], [3, 4, 6, 10], [1, 3, 4, 6, 10], [2, 3, 4, 6, 10], [1, 2, 3, 4, 6, 10], [5, 6, 10], [1, 5, 6, 10], [2, 5, 6, 10], [1, 2, 5, 6, 10], [3, 5, 6, 10], [1, 3, 5, 6, 10], [2, 3, 5, 6, 10], [1, 2, 3, 5, 6, 10], [4, 5, 6, 10], [1, 4, 5, 6, 10], [2, 4, 5, 6, 10], [1, 2, 4, 5, 6, 10], [3, 4, 5, 6, 10], [1, 3, 4, 5, 6, 10], [2, 3, 4, 5, 6, 10], [1, 2, 3, 4, 5, 6, 10], [7, 10], [1, 7, 10], [2, 7, 10], [1, 2, 7, 10], [3, 7, 10], [1, 3, 7, 10], [2, 3, 7, 10], [1, 2, 3, 7, 10], [4, 7, 10], [1, 4, 7, 10], [2, 4, 7, 10], [1, 2, 4, 7, 10], [3, 4, 7, 10], [1, 3, 4, 7, 10], [2, 3, 4, 7, 10], [1, 2, 3, 4, 7, 10], [5, 7, 10], [1, 5, 7, 10], [2, 5, 7, 10], [1, 2, 5, 7, 10], [3, 5, 7, 10], [1, 3, 5, 7, 10], [2, 3, 5, 7, 10], [1, 2, 3, 5, 7, 10], [4, 5, 7, 10], [1, 4, 5, 7, 10], [2, 4, 5, 7, 10], [1, 2, 4, 5, 7, 10], [3, 4, 5, 7, 10], [1, 3, 4, 5, 7, 10], [2, 3, 4, 5, 7, 10], [1, 2, 3, 4, 5, 7, 10], [6, 7, 10], [1, 6, 7, 10], [2, 6, 7, 10], [1, 2, 6, 7, 10], [3, 6, 7, 10], [1, 3, 6, 7, 10], [2, 3, 6, 7, 10], [1, 2, 3, 6, 7, 10], [4, 6, 7, 10], [1, 4, 6, 7, 10], [2, 4, 6, 7, 10], [1, 2, 4, 6, 7, 10], [3, 4, 6, 7, 10], [1, 3, 4, 6, 7, 10], [2, 3, 4, 6, 7, 10], [1, 2, 3, 4, 6, 7, 10], [5, 6, 7, 10], [1, 5, 6, 7, 10], [2, 5, 6, 7, 10], [1, 2, 5, 6, 7, 10], [3, 5, 6, 7, 10], [1, 3, 5, 6, 7, 10], [2, 3, 5, 6, 7, 10], [1, 2, 3, 5, 6, 7, 10], [4, 5, 6, 7, 10], [1, 4, 5, 6, 7, 10], [2, 4, 5, 6, 7, 10], [1, 2, 4, 5, 6, 7, 10], [3, 4, 5, 6, 7, 10], [1, 3, 4, 5, 6, 7, 10], [2, 3, 4, 5, 6, 7, 10], [1, 2, 3, 4, 5, 6, 7, 10], [8, 10], [1, 8, 10], [2, 8, 10], [1, 2, 8, 10], [3, 8, 10], [1, 3, 8, 10], [2, 3, 8, 10], [1, 2, 3, 8, 10], [4, 8, 10], [1, 4, 8, 10], [2, 4, 8, 10], [1, 2, 4, 8, 10], [3, 4, 8, 10], [1, 3, 4, 8, 10], [2, 3, 4, 8, 10], [1, 2, 3, 4, 8, 10], [5, 8, 10], [1, 5, 8, 10], [2, 5, 8, 10], [1, 2, 5, 8, 10], [3, 5, 8, 10], [1, 3, 5, 8, 10], [2, 3, 5, 8, 10], [1, 2, 3, 5, 8, 10], [4, 5, 8, 10], [1, 4, 5, 8, 10], [2, 4, 5, 8, 10], [1, 2, 4, 5, 8, 10], [3, 4, 5, 8, 10], [1, 3, 4, 5, 8, 10], [2, 3, 4, 5, 8, 10], [1, 2, 3, 4, 5, 8, 10], [6, 8, 10], [1, 6, 8, 10], [2, 6, 8, 10], [1, 2, 6, 8, 10], [3, 6, 8, 10], [1, 3, 6, 8, 10], [2, 3, 6, 8, 10], [1, 2, 3, 6, 8, 10], [4, 6, 8, 10], [1, 4, 6, 8, 10], [2, 4, 6, 8, 10], [1, 2, 4, 6, 8, 10], [3, 4, 6, 8, 10], [1, 3, 4, 6, 8, 10], [2, 3, 4, 6, 8, 10], [1, 2, 3, 4, 6, 8, 10], [5, 6, 8, 10], [1, 5, 6, 8, 10], [2, 5, 6, 8, 10], [1, 2, 5, 6, 8, 10], [3, 5, 6, 8, 10], [1, 3, 5, 6, 8, 10], [2, 3, 5, 6, 8, 10], [1, 2, 3, 5, 6, 8, 10], [4, 5, 6, 8, 10], [1, 4, 5, 6, 8, 10], [2, 4, 5, 6, 8, 10], [1, 2, 4, 5, 6, 8, 10], [3, 4, 5, 6, 8, 10], [1, 3, 4, 5, 6, 8, 10], [2, 3, 4, 5, 6, 8, 10], [1, 2, 3, 4, 5, 6, 8, 10], [7, 8, 10], [1, 7, 8, 10], [2, 7, 8, 10], [1, 2, 7, 8, 10], [3, 7, 8, 10], [1, 3, 7, 8, 10], [2, 3, 7, 8, 10], [1, 2, 3, 7, 8, 10], [4, 7, 8, 10], [1, 4, 7, 8, 10], [2, 4, 7, 8, 10], [1, 2, 4, 7, 8, 10], [3, 4, 7, 8, 10], [1, 3, 4, 7, 8, 10], [2, 3, 4, 7, 8, 10], [1, 2, 3, 4, 7, 8, 10], [5, 7, 8, 10], [1, 5, 7, 8, 10], [2, 5, 7, 8, 10], [1, 2, 5, 7, 8, 10], [3, 5, 7, 8, 10], [1, 3, 5, 7, 8, 10], [2, 3, 5, 7, 8, 10], [1, 2, 3, 5, 7, 8, 10], [4, 5, 7, 8, 10], [1, 4, 5, 7, 8, 10], [2, 4, 5, 7, 8, 10], [1, 2, 4, 5, 7, 8, 10], [3, 4, 5, 7, 8, 10], [1, 3, 4, 5, 7, 8, 10], [2, 3, 4, 5, 7, 8, 10], [1, 2, 3, 4, 5, 7, 8, 10], [6, 7, 8, 10], [1, 6, 7, 8, 10], [2, 6, 7, 8, 10], [1, 2, 6, 7, 8, 10], [3, 6, 7, 8, 10], [1, 3, 6, 7, 8, 10], [2, 3, 6, 7, 8, 10], [1, 2, 3, 6, 7, 8, 10], [4, 6, 7, 8, 10], [1, 4, 6, 7, 8, 10], [2, 4, 6, 7, 8, 10], [1, 2, 4, 6, 7, 8, 10], [3, 4, 6, 7, 8, 10], [1, 3, 4, 6, 7, 8, 10], [2, 3, 4, 6, 7, 8, 10], [1, 2, 3, 4, 6, 7, 8, 10], [5, 6, 7, 8, 10], [1, 5, 6, 7, 8, 10], [2, 5, 6, 7, 8, 10], [1, 2, 5, 6, 7, 8, 10], [3, 5, 6, 7, 8, 10], [1, 3, 5, 6, 7, 8, 10], [2, 3, 5, 6, 7, 8, 10], [1, 2, 3, 5, 6, 7, 8, 10], [4, 5, 6, 7, 8, 10], [1, 4, 5, 6, 7, 8, 10], [2, 4, 5, 6, 7, 8, 10], [1, 2, 4, 5, 6, 7, 8, 10], [3, 4, 5, 6, 7, 8, 10], [1, 3, 4, 5, 6, 7, 8, 10], [2, 3, 4, 5, 6, 7, 8, 10], [1, 2, 3, 4, 5, 6, 7, 8, 10], [9, 10], [1, 9, 10], [2, 9, 10], [1, 2, 9, 10], [3, 9, 10], [1, 3, 9, 10], [2, 3, 9, 10], [1, 2, 3, 9, 10], [4, 9, 10], [1, 4, 9, 10], [2, 4, 9, 10], [1, 2, 4, 9, 10], [3, 4, 9, 10], [1, 3, 4, 9, 10], [2, 3, 4, 9, 10], [1, 2, 3, 4, 9, 10], [5, 9, 10], [1, 5, 9, 10], [2, 5, 9, 10], [1, 2, 5, 9, 10], [3, 5, 9, 10], [1, 3, 5, 9, 10], [2, 3, 5, 9, 10], [1, 2, 3, 5, 9, 10], [4, 5, 9, 10], [1, 4, 5, 9, 10], [2, 4, 5, 9, 10], [1, 2, 4, 5, 9, 10], [3, 4, 5, 9, 10], [1, 3, 4, 5, 9, 10], [2, 3, 4, 5, 9, 10], [1, 2, 3, 4, 5, 9, 10], [6, 9, 10], [1, 6, 9, 10], [2, 6, 9, 10], [1, 2, 6, 9, 10], [3, 6, 9, 10], [1, 3, 6, 9, 10], [2, 3, 6, 9, 10], [1, 2, 3, 6, 9, 10], [4, 6, 9, 10], [1, 4, 6, 9, 10], [2, 4, 6, 9, 10], [1, 2, 4, 6, 9, 10], [3, 4, 6, 9, 10], [1, 3, 4, 6, 9, 10], [2, 3, 4, 6, 9, 10], [1, 2, 3, 4, 6, 9, 10], [5, 6, 9, 10], [1, 5, 6, 9, 10], [2, 5, 6, 9, 10], [1, 2, 5, 6, 9, 10], [3, 5, 6, 9, 10], [1, 3, 5, 6, 9, 10], [2, 3, 5, 6, 9, 10], [1, 2, 3, 5, 6, 9, 10], [4, 5, 6, 9, 10], [1, 4, 5, 6, 9, 10], [2, 4, 5, 6, 9, 10], [1, 2, 4, 5, 6, 9, 10], [3, 4, 5, 6, 9, 10], [1, 3, 4, 5, 6, 9, 10], [2, 3, 4, 5, 6, 9, 10], [1, 2, 3, 4, 5, 6, 9, 10], [7, 9, 10], [1, 7, 9, 10], [2, 7, 9, 10], [1, 2, 7, 9, 10], [3, 7, 9, 10], [1, 3, 7, 9, 10], [2, 3, 7, 9, 10], [1, 2, 3, 7, 9, 10], [4, 7, 9, 10], [1, 4, 7, 9, 10], [2, 4, 7, 9, 10], [1, 2, 4, 7, 9, 10], [3, 4, 7, 9, 10], [1, 3, 4, 7, 9, 10], [2, 3, 4, 7, 9, 10], [1, 2, 3, 4, 7, 9, 10], [5, 7, 9, 10], [1, 5, 7, 9, 10], [2, 5, 7, 9, 10], [1, 2, 5, 7, 9, 10], [3, 5, 7, 9, 10], [1, 3, 5, 7, 9, 10], [2, 3, 5, 7, 9, 10], [1, 2, 3, 5, 7, 9, 10], [4, 5, 7, 9, 10], [1, 4, 5, 7, 9, 10], [2, 4, 5, 7, 9, 10], [1, 2, 4, 5, 7, 9, 10], [3, 4, 5, 7, 9, 10], [1, 3, 4, 5, 7, 9, 10], [2, 3, 4, 5, 7, 9, 10], [1, 2, 3, 4, 5, 7, 9, 10], [6, 7, 9, 10], [1, 6, 7, 9, 10], [2, 6, 7, 9, 10], [1, 2, 6, 7, 9, 10], [3, 6, 7, 9, 10], [1, 3, 6, 7, 9, 10], [2, 3, 6, 7, 9, 10], [1, 2, 3, 6, 7, 9, 10], [4, 6, 7, 9, 10], [1, 4, 6, 7, 9, 10], [2, 4, 6, 7, 9, 10], [1, 2, 4, 6, 7, 9, 10], [3, 4, 6, 7, 9, 10], [1, 3, 4, 6, 7, 9, 10], [2, 3, 4, 6, 7, 9, 10], [1, 2, 3, 4, 6, 7, 9, 10], [5, 6, 7, 9, 10], [1, 5, 6, 7, 9, 10], [2, 5, 6, 7, 9, 10], [1, 2, 5, 6, 7, 9, 10], [3, 5, 6, 7, 9, 10], [1, 3, 5, 6, 7, 9, 10], [2, 3, 5, 6, 7, 9, 10], [1, 2, 3, 5, 6, 7, 9, 10], [4, 5, 6, 7, 9, 10], [1, 4, 5, 6, 7, 9, 10], [2, 4, 5, 6, 7, 9, 10], [1, 2, 4, 5, 6, 7, 9, 10], [3, 4, 5, 6, 7, 9, 10], [1, 3, 4, 5, 6, 7, 9, 10], [2, 3, 4, 5, 6, 7, 9, 10], [1, 2, 3, 4, 5, 6, 7, 9, 10], [8, 9, 10], [1, 8, 9, 10], [2, 8, 9, 10], [1, 2, 8, 9, 10], [3, 8, 9, 10], [1, 3, 8, 9, 10], [2, 3, 8, 9, 10], [1, 2, 3, 8, 9, 10], [4, 8, 9, 10], [1, 4, 8, 9, 10], [2, 4, 8, 9, 10], [1, 2, 4, 8, 9, 10], [3, 4, 8, 9, 10], [1, 3, 4, 8, 9, 10], [2, 3, 4, 8, 9, 10], [1, 2, 3, 4, 8, 9, 10], [5, 8, 9, 10], [1, 5, 8, 9, 10], [2, 5, 8, 9, 10], [1, 2, 5, 8, 9, 10], [3, 5, 8, 9, 10], [1, 3, 5, 8, 9, 10], [2, 3, 5, 8, 9, 10], [1, 2, 3, 5, 8, 9, 10], [4, 5, 8, 9, 10], [1, 4, 5, 8, 9, 10], [2, 4, 5, 8, 9, 10], [1, 2, 4, 5, 8, 9, 10], [3, 4, 5, 8, 9, 10], [1, 3, 4, 5, 8, 9, 10], [2, 3, 4, 5, 8, 9, 10], [1, 2, 3, 4, 5, 8, 9, 10], [6, 8, 9, 10], [1, 6, 8, 9, 10], [2, 6, 8, 9, 10], [1, 2, 6, 8, 9, 10], [3, 6, 8, 9, 10], [1, 3, 6, 8, 9, 10], [2, 3, 6, 8, 9, 10], [1, 2, 3, 6, 8, 9, 10], [4, 6, 8, 9, 10], [1, 4, 6, 8, 9, 10], [2, 4, 6, 8, 9, 10], [1, 2, 4, 6, 8, 9, 10], [3, 4, 6, 8, 9, 10], [1, 3, 4, 6, 8, 9, 10], [2, 3, 4, 6, 8, 9, 10], [1, 2, 3, 4, 6, 8, 9, 10], [5, 6, 8, 9, 10], [1, 5, 6, 8, 9, 10], [2, 5, 6, 8, 9, 10], [1, 2, 5, 6, 8, 9, 10], [3, 5, 6, 8, 9, 10], [1, 3, 5, 6, 8, 9, 10], [2, 3, 5, 6, 8, 9, 10], [1, 2, 3, 5, 6, 8, 9, 10], [4, 5, 6, 8, 9, 10], [1, 4, 5, 6, 8, 9, 10], [2, 4, 5, 6, 8, 9, 10], [1, 2, 4, 5, 6, 8, 9, 10], [3, 4, 5, 6, 8, 9, 10], [1, 3, 4, 5, 6, 8, 9, 10], [2, 3, 4, 5, 6, 8, 9, 10], [1, 2, 3, 4, 5, 6, 8, 9, 10], [7, 8, 9, 10], [1, 7, 8, 9, 10], [2, 7, 8, 9, 10], [1, 2, 7, 8, 9, 10], [3, 7, 8, 9, 10], [1, 3, 7, 8, 9, 10], [2, 3, 7, 8, 9, 10], [1, 2, 3, 7, 8, 9, 10], [4, 7, 8, 9, 10], [1, 4, 7, 8, 9, 10], [2, 4, 7, 8, 9, 10], [1, 2, 4, 7, 8, 9, 10], [3, 4, 7, 8, 9, 10], [1, 3, 4, 7, 8, 9, 10], [2, 3, 4, 7, 8, 9, 10], [1, 2, 3, 4, 7, 8, 9, 10], [5, 7, 8, 9, 10], [1, 5, 7, 8, 9, 10], [2, 5, 7, 8, 9, 10], [1, 2, 5, 7, 8, 9, 10], [3, 5, 7, 8, 9, 10], [1, 3, 5, 7, 8, 9, 10], [2, 3, 5, 7, 8, 9, 10], [1, 2, 3, 5, 7, 8, 9, 10], [4, 5, 7, 8, 9, 10], [1, 4, 5, 7, 8, 9, 10], [2, 4, 5, 7, 8, 9, 10], [1, 2, 4, 5, 7, 8, 9, 10], [3, 4, 5, 7, 8, 9, 10], [1, 3, 4, 5, 7, 8, 9, 10], [2, 3, 4, 5, 7, 8, 9, 10], [1, 2, 3, 4, 5, 7, 8, 9, 10], [6, 7, 8, 9, 10], [1, 6, 7, 8, 9, 10], [2, 6, 7, 8, 9, 10], [1, 2, 6, 7, 8, 9, 10], [3, 6, 7, 8, 9, 10], [1, 3, 6, 7, 8, 9, 10], [2, 3, 6, 7, 8, 9, 10], [1, 2, 3, 6, 7, 8, 9, 10], [4, 6, 7, 8, 9, 10], [1, 4, 6, 7, 8, 9, 10], [2, 4, 6, 7, 8, 9, 10], [1, 2, 4, 6, 7, 8, 9, 10], [3, 4, 6, 7, 8, 9, 10], [1, 3, 4, 6, 7, 8, 9, 10], [2, 3, 4, 6, 7, 8, 9, 10], [1, 2, 3, 4, 6, 7, 8, 9, 10], [5, 6, 7, 8, 9, 10], [1, 5, 6, 7, 8, 9, 10], [2, 5, 6, 7, 8, 9, 10], [1, 2, 5, 6, 7, 8, 9, 10], [3, 5, 6, 7, 8, 9, 10], [1, 3, 5, 6, 7, 8, 9, 10], [2, 3, 5, 6, 7, 8, 9, 10], [1, 2, 3, 5, 6, 7, 8, 9, 10], [4, 5, 6, 7, 8, 9, 10], [1, 4, 5, 6, 7, 8, 9, 10], [2, 4, 5, 6, 7, 8, 9, 10], [1, 2, 4, 5, 6, 7, 8, 9, 10], [3, 4, 5, 6, 7, 8, 9, 10], [1, 3, 4, 5, 6, 7, 8, 9, 10], [2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]

In [ ]:
def bruteForceCalori(sort_profit,kalori):
  arr = powerset(items)
  max = 0
  max_budget = 0
  max_profit = 0
  max_karbo = 0
 
  for i in range(len(arr)):
    total = 0
    budget = 0
    total_profit = 0
    total_kalori = 0
    total_karbo = 0
    for j in range(len(arr[i])):
      total += sort_profit.Kalori[arr[i][j]-1]
      budget += sort_profit.Harga[arr[i][j]-1]
      total_profit += sort_profit.Profit[arr[i][j]-1]
      total_karbo += sort_profit.Karbohidrat[arr[i][j]-1]
    if max < total and total <= kalori and budget <= 100000:
        max_profit = total_profit
        max = total
        max_budget = budget
        max_karbo = total_karbo
        makanan = []
        for k in range(j+1):
          makanan.append(sort_profit.Makanan[arr[i][k]-1])
  print("Himpunan Solusi:",makanan)
  print("Total Biaya:",max_budget)
  print("Total Profit",max_profit)

bruteForceCalori(sort_profit,2000)

Himpunan Solusi: ['bebek', 'Ayam dada', 'Daging Sapi', 'Keju Cheddar', 'Alpukat', 'Salmon', 'brokoli']
Total Biaya: 99000
Total Profit 146.49999999999997

### **Greedy**

In [ ]:
def Greedy(sort_profit):
  total_kalori = 0
  total_harga = 0
  total_profit = 0
  nama = []
  i = 0
  while i < (len(sort_profit)-1): 
    if total_harga + sort_profit.Harga[i] <= 100000 and total_kalori + sort_profit.Kalori[i]:
      total_kalori += sort_profit.Kalori[i]
      total_harga += sort_profit.Harga[i]
      total_profit += sort_profit.Profit[i]
      nama += [sort_profit.Makanan[i]]
    i = i+1
  print("Himpunan Solusi :", nama)
  print("Total Biaya :", total_harga)
  print("Total Kalori:", total_kalori)
  print("Total Profit", total_profit)
Greedy(sort_profit)

Himpunan Solusi : ['bebek', 'Ayam dada', 'Daging Sapi', 'Keju Cheddar', 'Alpukat', 'Salmon', 'brokoli']
Total Biaya : 99000
Total Kalori: 1973
Total Profit 146.49999999999997

In [ ]:
sort_harga

   No         Makanan  Kalori  Karbohidrat  Harga  Profit
0   1         Alpukat     102            0   5000    20.4
1   9    Keju Cheddar     114            1   5000    22.8
2   2       Ayam dada     332            0  10000    33.2
3   3           Bayam      19            3  10000     1.9
4   5         brokoli      27            3  10000     2.7
5   7   Jamur Kancing      15            2  10000     1.5
6   8  Kacang Panjang      22            4  10000     1.5
7   4           bebek     641            0  19000    33.8
8   6     Daging Sapi     500            0  20000    25.0
9  10          Salmon     257            0  30000     8.6

In [ ]:
def Greedy(sort_harga):
  total_kalori = 0
  total_harga = 0
  total_profit = 0
  nama = []
  i = 0
  while i < (len(sort_harga)-1): 
    if total_harga + sort_harga.Harga[i] <= 100000:
      total_kalori += sort_harga.Kalori[i]
      total_harga += sort_harga.Harga[i]
      total_profit += sort_harga.Profit[i]
      nama += [sort_harga.Makanan[i]]
    i = i+1
  print("Himpunan Solusi :", nama)
  print("Total Biaya :", total_harga)
  print("Total Kalori:", total_kalori)
  print("Total Profit", total_profit)
Greedy(sort_harga)

Himpunan Solusi : ['Alpukat', 'Keju Cheddar', 'Ayam dada', 'Bayam', 'brokoli', 'Jamur Kancing', 'Kacang Panjang', 'bebek', 'Daging Sapi']
Total Biaya : 99000
Total Kalori: 1772
Total Profit 142.8